services:
  - type: web
    name: surebet-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    # 環境變數改為在 Render 控制台設定，避免敏感資料外洩
    # envVars:
    #   - key: TELEGRAM_BOT_TOKEN
    #     value: 請在 Render 控制台手動設定
    #   - key: TELEGRAM_CHAT_ID
    #     value: 請在 Render 控制台手動設定
