services:
  - type: web
    name: surebet-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7967768701:AAGbMMmzXm-UUnyp82NV3Ir0pbLkEgfhPjA
      - key: TELEGRAM_CHAT_ID
        value: "7120810623"
    plan: free

  - type: worker
    name: telegram-listener
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_listener.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7967768701:AAGbMMmzXm-UUnyp82NV3Ir0pbLkEgfhPjA
      - key: TELEGRAM_CHAT_ID
        value: "7120810623"
    plan: free

